/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rst_gpioi2c_i2c_JNI_I2C_ReadWrite */

#ifndef _Included_com_rst_gpioi2c_i2c_JNI_I2C_ReadWrite
#define _Included_com_rst_gpioi2c_i2c_JNI_I2C_ReadWrite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rst_gpioi2c_i2c_JNI_I2C_ReadWrite
 * Method:    cWrite
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_rst_gpioi2c_i2c_JNI_I2C_1ReadWrite_cWrite
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_rst_gpioi2c_i2c_JNI_I2C_ReadWrite
 * Method:    cRead
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_rst_gpioi2c_i2c_JNI_I2C_1ReadWrite_cRead
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
