/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rst_gpioi2c_gpio_JNI_Press */

#ifndef _Included_com_rst_gpioi2c_gpio_JNI_Press
#define _Included_com_rst_gpioi2c_gpio_JNI_Press
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rst_gpioi2c_gpio_JNI_Press
 * Method:    cPress
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rst_gpioi2c_gpio_JNI_Press_cPress
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rst_gpioi2c_gpio_JNI_Press
 * Method:    cStopInterrupt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rst_gpioi2c_gpio_JNI_Press_cStopInterrupt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
