/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ReadJNI */

#ifndef _Included_ReadJNI
#define _Included_ReadJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ReadJNI
 * Method:    cRead
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_ReadJNI_cRead
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
