/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WriteJNI */

#ifndef _Included_WriteJNI
#define _Included_WriteJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WriteJNI
 * Method:    cWrite
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_WriteJNI_cWrite
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
