/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GPIOMethods */

#ifndef _Included_GPIOMethods
#define _Included_GPIOMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GPIOMethods
 * Method:    cExport
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_GPIOMethods_cExport
  (JNIEnv *, jobject, jint);

/*
 * Class:     GPIOMethods
 * Method:    cUnExport
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_GPIOMethods_cUnExport
  (JNIEnv *, jobject, jint);

/*
 * Class:     GPIOMethods
 * Method:    cDirection
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_GPIOMethods_cDirection
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     GPIOMethods
 * Method:    cGPIOWrite
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_GPIOMethods_cGPIOWrite
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     GPIOMethods
 * Method:    cGPIORead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_GPIOMethods_cGPIORead
  (JNIEnv *, jobject, jint);

/*
 * Class:     GPIOMethods
 * Method:    cReadDirection
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_GPIOMethods_cReadDirection
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
