/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Press */

#ifndef _Included_Press
#define _Included_Press
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Press
 * Method:    cPress
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Press_cPress
  (JNIEnv *, jobject, jint);

/*
 * Class:     Press
 * Method:    cStopInterrupt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Press_cStopInterrupt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
