/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Direction */

#ifndef _Included_Direction
#define _Included_Direction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Direction
 * Method:    cDirection
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Direction_cDirection
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
