/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Export */

#ifndef _Included_Export
#define _Included_Export
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Export
 * Method:    cExport
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Export_cExport
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
