/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GPIORead */

#ifndef _Included_GPIORead
#define _Included_GPIORead
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GPIORead
 * Method:    cGPIORead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_GPIORead_cGPIORead
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
