/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GPIOWrite */

#ifndef _Included_GPIOWrite
#define _Included_GPIOWrite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GPIOWrite
 * Method:    cGPIOWrite
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_GPIOWrite_cGPIOWrite
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
