/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class light */

#ifndef _Included_light
#define _Included_light
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     light
 * Method:    fact
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_light_fact
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
