/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UnExport */

#ifndef _Included_UnExport
#define _Included_UnExport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UnExport
 * Method:    cUnExport
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_UnExport_cUnExport
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
